version: '2'
services:
  app:
    container_name: errbuddy-app
    env_file: .env
    mem_limit: 4g
    hostname: ${HOSTNAME}
    image: openjdk:8-jdk
    ports:
    - 9000:9000
    depends_on:
    - redis
    - elasticsearch
    - mariadb
    dns: 8.8.8.8
    links:
     - mariadb
     - redis
     - elasticsearch
    volumes:
      - ./start-latest-stable.sh:/opt/start-latest-stable.sh
      - ./default-config.groovy:/opt/errbuddy/errbuddy.groovy
      #TODO: find out how to have a seperate volume for scaled servers
    command: /bin/bash -c "bash /opt/start-latest.sh"
