version: '2'
services:
  app:
    container_name: errbuddy-app
    hostname: ${HOSTNAME}
    env_file: .env
    mem_limit: 3g
    image: openjdk:8-jdk
    ports:
    - 9000:9000
    depends_on:
    - redis
    - elasticsearch
    - mariadb
    dns: 8.8.8.8
    links:
     - mariadb
     - redis
     - elasticsearch
    volumes:
      - .:/opt/app
      - ./default-config.groovy:/opt/errbuddy/errbuddy.groovy
      - .data/.gradle:/root/.gradle:rw
      - .data/build:/opt/app/build:rw
      - .data/nodejs:/opt/app/.nodejs:rw
      - .data/node_moudels:/opt/app/node_modules:rw
    command: /bin/bash -c "cd /opt/errbuddy/ && wget https://s3.eu-central-1.amazonaws.com/errbuddy-devel/current.war && java -Dgrails.env=prod -Derrbuddy.mysql.password=${MYSQL_PASSWORD} -Derrbuddy.serverUrl=${SERVER_URL} -jar current.war"
