version: '2'
services:
  app:
    container_name: errbuddy-app
    env_file: .env
    mem_limit: 4g
    hostname: ${HOSTNAME}
    image: openjdk:8-jdk
    ports:
    - 9000:9000
    depends_on:
    - redis
    - elasticsearch
    - mariadb
    dns: 8.8.8.8
    links:
     - mariadb
     - redis
     - elasticsearch
    volumes:
      - ./start-latest-stable.sh:/opt/start-latest-stable.sh
      - ./default-config.groovy:/opt/errbuddy/errbuddy.groovy
      #TODO: find out how to have a seperate volume for scaled servers
    command: /bin/bash -c "bash /opt/start-latest-stable.sh"
  redis:
    container_name: errbuddy_redis
    image: redis
  elasticsearch:
    container_name: errbuddy_es
    image: elasticsearch:1.7.5
    volumes:
      - .data/elasticsearch:/usr/share/elasticsearch/data:rw
  mariadb:
    container_name: errbuddy_mariadb
    env_file: .env
    image: mariadb:10.0
#    ports:
#      - 127.0.0.1:3306:3306 # makes it easier to create backups
    volumes:
      - .data/mysql:/var/lib/mysql:rw
      - ./etc/mysql/:/etc/mysql/conf.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=errbuddy
      - MYSQL_USER=errbuddy
